# Generated by Django 5.0.7 on 2024-09-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Describtion',
            new_name='Description',
        ),
    ]
