# Generated by Django 5.0.7 on 2024-09-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_describtion_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='describtion',
            new_name='description',
        ),
    ]
